spring:
    config:
        import:
            - 'classpath:datasource-temporary.yaml'
springdoc:
    swagger-ui:
        path: /swagger-ui/index.html
        tags-sorter: alpha
        disable-swagger-default-url: true
        display-request-duration: true
        display-operation-id: false
        operations-sorter: alpha
        enabled: true
    packages-to-scan:
        - "com.base.controller"
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    enable-javadoc: true
    show-actuator: true
