spring:
    application:
      name: "base"
    profiles:
        active:
            - temporary
            - local
            - stage
            - production
    config:
        import: 'classpath:common.yaml'
